# Generated by Django 5.1.5 on 2025-01-17 11:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mricase',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mricase',
            name='decision',
            field=models.CharField(choices=[('Y', 'Tumor'), ('N', 'No Tumor')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mricase',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mricase',
            name='radiologist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mri_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mricase',
            name='risk',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mricase',
            name='scan_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
