# Generated by Django 5.1.5 on 2025-01-17 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mricase_birth_date_mricase_decision_mricase_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mricase',
            name='scan',
            field=models.ImageField(default='', upload_to='scans/'),
        ),
        migrations.AlterField(
            model_name='mricase',
            name='birth_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='mricase',
            name='radiologist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mricases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mricase',
            name='scan_date',
            field=models.DateField(default=''),
        ),
    ]
