# Generated by Django 5.1.5 on 2025-01-17 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mricase_scan_alter_mricase_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mricase',
            name='radiologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mricases', to=settings.AUTH_USER_MODEL),
        ),
    ]
