# Generated by Django 5.1.5 on 2025-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mricase_radiologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mricase',
            name='decision',
            field=models.CharField(choices=[('Y', 'Tumor'), ('N', 'No Tumor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mricase',
            name='risk',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=10),
        ),
    ]
